version: "3.9"
services:
  postgres:
    image: bitnami/postgresql:latest
    # NOTE: volumes section can be removed if not needed
    volumes:
      - axum-template-db:/bitnami/postgresql
      - ./init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql
    ports:
      - '15432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=axum_template_db
    restart: unless-stopped

  postgres-test:
    image: bitnami/postgresql:latest
    ports:
      - '15433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=axum_template_db
    restart: always

# NOTE: volumes section can be removed if not needed
volumes:
  axum-template-db:
